### ISSUE TITLE
problem viewing trailer in window

### ISSUE THREAD

**Issue by Alex230177** [beatmasterRS/skin.arctic.zephyr.mod#855] opened 2022-09-18 20:22 UTC
hi, I have a problem in viewing the trailers in the window, even if I set view trailer in window it starts me both in the window and as a background practically as if they were 2 trailers and at the bottom I see the other trailer scroll ruining the whole view. i also tried to enlarge the png image of the trailer window to try to hide it but it still remains the same

**Comment by beatmasterRS** [comment] 2022-09-18 20:25
Could you please provide Screenshots/Photos?

**Comment by Alex230177** [comment] 2022-09-19 08:47
![Trailer in window](https://user-images.githubusercontent.com/87814427/190980828-f0d6ca9c-2b5a-4768-8784-4adc77c2e3cb.jpg)


I also tried to uninstall and reinstall the skin, however it does it with some trailers maybe it's a matter of format

**Comment by beatmasterRS** [comment] 2022-09-19 09:01
Okay thank you. Please enable "debugging" in  skin settings > Arctic: zephyr - Reloaded. Also enable "Show debug information" and "Extended debugging information".

Now please go to library or home and wait for a trailer to auto start. When the trailer is playing, please make a photo/screenshot, so i can see, whats going on with the background.

You should get something like this:
![screenshot01256](https://user-images.githubusercontent.com/3855273/190983607-597e3619-f27f-44e3-b19c-70dedf3d9017.png)

**Comment by Alex230177** [comment] 2022-09-19 09:15
![1](https://user-images.githubusercontent.com/87814427/190985412-e51a4e10-e2bd-4b27-b0b6-42b09746ddbd.jpg)
![2](https://user-images.githubusercontent.com/87814427/190985473-db75635a-a537-4e82-874f-20ab0d8b0543.jpg)

The 1 is what you see double, the 2 is seen in the window,

I also wanted to inform you that in the view (View_51_BigWide) at line 750 I added a Left 100 in my file because the artist name was all shifted to the left and went above the other tabs

**Comment by beatmasterRS** [comment] 2022-09-19 09:26
Thank you. From the skin side everything seems to be okay. Are you using a plex client or something like that? I'm asking, because a few month ago, a user has the same issues with auto playing trailers and the trailer starts always in fullscreen.

>>I also wanted to inform you that in the view (View_51_BigWide) at line 750 I added a Left 100 in my file because the artist name was all shifted to the left and went above the other tabs

Could you please provide a screenshot?

**Comment by Alex230177** [comment] 2022-09-19 09:42
No I don't use anything it's all local, my trailers are local too.

as for Big view I am attaching the photos.

![with left 100 in line 750](https://user-images.githubusercontent.com/87814427/190990567-7df31e95-ee4c-444c-84b6-b279bfda9df9.JPG)
![without left 100 in line 750](https://user-images.githubusercontent.com/87814427/190990568-dc253dd3-5a16-4f68-87dd-16153453e553.JPG)

**Comment by beatmasterRS** [comment] 2022-09-19 10:08
>>as for Big view I am attaching the photos.

I could not reproduce the issue with overlapping artist. Tested on coreelec and windows. What version of the skin do you use? 

>>No I don't use anything it's all local, my trailers are local too.

Could you please check the status of the follwing settings?
Skin settings > extras > hidden video window to prevent audio errors
Skin settings > background > show now playing video in background

**Comment by Alex230177** [comment] 2022-09-19 10:26
Solved I set
 Skin settings> extras> hidden video window to prevent audio errors
Skin settings> background> now show the video playing in the background
Perfect thanks.
however if you are interested in the banner display I have added the clearlogo it looks more captivating, what can I do I love beautiful things and I am a graphics fanatic. (-:

![clearlogo banner view](https://user-images.githubusercontent.com/87814427/190998081-07b5dac6-e1dd-4533-9e17-4a05073711ca.JPG)

**Comment by beatmasterRS** [comment] 2022-09-19 12:35
Glad to hear, that its working now :) The i will close this issue

**Closed by beatmasterRS** 2022-09-19 12:35 UTC
Labels: Kodi 19
